"""Add conversation_state to Customer

Revision ID: 0c2d3c0238fc
Revises: 221cba837fa8
Create Date: 2026-05-09 13:09:04.330731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c2d3c0238fc'
down_revision: Union[str, None] = '221cba837fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('conversation_state', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'conversation_state')
    # ### end Alembic commands ###
