"""create_products

Revision ID: 2e6924e156eb
Revises: 
Create Date: 2026-04-19 13:12:35.584745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e6924e156eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('original_image_url', sa.Text(), nullable=False),
    sa.Column('qr_image_url', sa.Text(), nullable=True),
    sa.Column('qr_payload', sa.Text(), nullable=True),
    sa.Column('fallback_product_id', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fallback_product_id')
    )
    op.create_index('ix_products_deleted_at', 'products', ['deleted_at'], unique=False)
    op.create_index('ix_products_fallback_product_id', 'products', ['fallback_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_fallback_product_id', table_name='products')
    op.drop_index('ix_products_deleted_at', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
